name: main

on:
    workflow_dispatch:
    schedule:
        - cron: "7  0 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: windows-latest
        if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'

            - name: "install Dependency"
              run: |
                  pip install -r ./requirements.txt

            - name: "run sypy.py"
              run: python Sign_WenShuShu_selenium.py
              env:
                  USER: ${{ secrets.USER }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
